services:

  uoc_assistant:
    # image: ghcr.io/pauserratgutierrez/uoc-assistant/uoc_assistant:latest
    build:
      context: ./containers/assistant
      dockerfile: Dockerfile
    container_name: uoc_assistant
    restart: on-failure
    env_file:
      - .env
    depends_on:
      uoc_mysql:
        condition: service_healthy
    networks:
      - uoc_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health/status"]
      interval: 5m # Periodically check once healthy
      start_period: 10s # Delay 30 seconds to let MySQL initialize
      start_interval: 5s # Periodically check during the start period
      retries: 2 # Marked as unhealthy after consecutive failures
      timeout: 2s # Total time for each check

  uoc_discord_bot:
    # image: ghcr.io/pauserratgutierrez/uoc-assistant/uoc_discord_bot:latest
    build:
      context: ./containers/discord
      dockerfile: Dockerfile
    container_name: uoc_discord_bot
    restart: on-failure
    env_file:
      - .env
    depends_on:
      uoc_mysql:
        condition: service_healthy
      uoc_assistant:
        condition: service_healthy
    networks:
      - uoc_network

  uoc_mysql:
    # image: ghcr.io/pauserratgutierrez/uoc-assistant/uoc_mysql:latest
    build:
      context: ./containers/database
      dockerfile: Dockerfile
    container_name: uoc_mysql
    restart: on-failure
    env_file:
      - .env
    environment:
      MYSQL_TCP_PORT: "${MYSQL_PORT}"
    networks:
      - uoc_network
    volumes:
      - uoc_mysql_data:/var/lib/mysql
      - ./containers/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql # Initialize db schema on first run if data volume is empty
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --execute='USE ${MYSQL_DATABASE}; SELECT 1;'"]
      interval: 5m # Periodically check once healthy
      start_period: 30s # Delay 30 seconds to let MySQL initialize
      start_interval: 5s # Periodically check during the start period
      retries: 3 # Marked as unhealthy after consecutive failures
      timeout: 2s # Total time for each check

  uoc_mysql_backup:
    # image: ghcr.io/pauserratgutierrez/uoc-assistant/uoc_mysql:latest
    build:
      context: ./containers/database
      dockerfile: Dockerfile
    container_name: uoc_mysql_backup
    env_file:
      - .env
    depends_on:
      uoc_mysql:
        condition: service_healthy
    networks:
      - uoc_network
    entrypoint: /bin/sh -c "/scripts/mysql_backup.sh"
    volumes:
      - ./scripts/mysql_backup.sh:/scripts/mysql_backup.sh
      - ./backups:/backups
    restart: no

networks:
  uoc_network:

volumes:
  uoc_mysql_data: