name: Dataset Update

on:
  # schedule:
  #   - cron: '0 0 1,8,15,22 * *' # Run at 12:00 AM UTC on the 1st, 8th, 15th, and 22nd of every month (4 times a month)
  workflow_dispatch: # Allows manual triggering from the GitHub UI

concurrency:
  group: dataset-update
  cancel-in-progress: true

permissions:
  contents: write
  actions: write

jobs:
  main:
    runs-on: ubuntu-latest

    env:
      PROJECT_PATH: dataset
      NODE_CMD: npm run start

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1.7.3
        id: chrome
        with:
          chrome-version: stable
          install-dependencies: true

      - name: Setup Node
        uses: actions/setup-node@v4.3.0
        with:
          node-version: '22.15.0'
          cache: 'npm'
          cache-dependency-path: ${{ env.PROJECT_PATH }}/package-lock.json

      - name: Install NPM deps
        working-directory: ${{ env.PROJECT_PATH }}
        env:
          PUPPETEER_SKIP_DOWNLOAD: 'true'
        run: npm ci

      - name: Debug curl
        run: curl -I https://uoc.edu/ca

      - name: Run extractor
        working-directory: ${{ env.PROJECT_PATH }}
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.chrome.outputs.chrome-path }}
        run: ${{ env.NODE_CMD }}

      - name: Stamp run
        id: stamp
        if: success()
        run: echo "DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Commit & push data if changed
        if: success()
        run: |
          git config --global user.name  "Scheduled Dataset Update"
          git config --global user.email "github-actions@github.com"
          
          git add ${{ env.PROJECT_PATH }}/data/*

          if git diff --quiet && git diff --staged --quiet; then
            echo "No data changes – nothing to commit."
          else
            git commit -m "Dataset update – $DATE"
            git push
          fi